const x = 10

try {
    
    console.log("tudo certo");

} catch (error) {
    
    console.log(` Erro: ${error}`);

}